name: Build site

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'src/**'
      - 'pages/**'

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git add .
      - run: git commit --allow-empty -m "Rebuild site"
      - run: git push origin
